######服务器参数############
server:
  port: 8000
  servlet:
    session:
      timeout: 1800
    context-path: /
        
  tomcat:
    uri-encoding: UTF-8

logging:
  level:
    com.jeekhan.wx: DEBUG
    
spring:
  servlet:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb
######微信参数############
wxmp:
#userId 公众号
  PUBLIC-USER-ID: gh_ed70fd57008b
#appId
  APPID: wx8864bd7398aa5270
#appSecret
  APPSECRET: c2c15a91c950e8a6fc106192b044adfb
#token
  TOKEN: 1314
 #微信管理平台访问 
  wxmp-server-url: 'http://172.18.235.107:9000'
  jsapi-sign-url: '/jsapi/sign'
  
######业务参数-摩放优选服务中心访问############
mfyx:
  mfyx-server-url: 'http://172.18.235.107:8080'
  user-basic-get-url: '/user/get'
  user-basic-update-url: '/user/update'
  spread-qrcode-url: '/qrcode/spread'
  vip-basic-get-url: '/vip/get'
  
  partner-get-url: '/partner/get/byuser/'
  partner-create-url: '/partner/create'
  partner-update-url: '/partner/update'
  partner-change-status-url: '/partner//changeStatus'
  partner-review-url: '/partner/review'
  
  city-get-provinces-url: '/city/province/getall'
  city-get-cities-url: '/city/city/getbyprov/'
  city-get-areas-url: '/city/area/getbycity/'

  
######系统参数############  
sys:
  local-server-url: 'http://172.18.235.107:8000'
  tmp-file-dir: '/tmp/wxmp/'
  qrcode-file-dir: '/var/wxmp/qrcode/'
  material-file-dir: '/var/wxmp/material/'
  kf-headimg-dir: '/var/wxmp/headimg/'
  wxmenu-file-dir: '/var/wxmp/wxmenu/'
  
  
  