######服务器参数############
server:
  port: 8000
  servlet:
    session:
      timeout: 1800
    context-path: /
        
  tomcat:
    uri-encoding: UTF-8

logging:
  level:
    com.jeekhan.wx: DEBUG
    
spring:
  servlet:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb
######微信参数############
wx:
#userId 公众号
  PUBLIC-USER-ID: gh_613e2c864c97
#appId
  APPID: wx34a58dad7a6542ca
#appSecret
  APPSECRET: f49ce34b7d5db1532968212bb3ec5249
#token
  TOKEN: 1314
#state
  STATE: 'mfyxwx'
  
 #微信管理平台访问 
wxmp:
  wxmp-server-url: 'http://172.18.235.107:9000'
  jsapi-sign-url: '/jsapi/sign' 
  
######业务参数-摩放优选服务中心访问############
mfyx:
  mfyx-server-url: 'http://172.18.235.107:8080'
  messmp-server-url: 'http://172.18.235.107:8888'
  
  user-basic-get-url: '/user/get'
  user-basic-getbyid-url: '/user/getbyid/{userId}'
  user-basic-create-url: '/user/create'
  user-basic-update-url: '/user/update'
  user-spread-qrcode-url: '/qrcode/spread'
  user-headimg-upload-url: '/user/headimg/upload/{userId}'
  user-headimg-show-url: '/user/headimg/show/{userId}'
  
  vip-basic-get-url: '/vip/get/{vipId}'
  vip-cash-flow-getall-url: '/vip/flow/getall'
  vip-upd-phone-url: '/vip/{vipId}/updphone'
  vip-upd-email-url: '/vip/{vipId}/updemail'
  vip-reset-pwd-url: '/vip/{vipId}/resetpwd'
  vip-upd-pwd-url: '/vip/{vipId}/updpwd'
  vip-phone-vericode-get-url: '/sms/vericode/send'
  vip-email-vericode-get-url: '/email/vericode/send'
  
  settle-account-save-url: '/settle/{vipId}/saveact'
  settle-account-delete-url: '/settle/{vipId}/delete'
  settle-account-getall-url: '/settle/{vipId}/getall'
  
  partner-get-byvip-url: '/partner/get/byvip/'
  partner-get-byid-url: '/partner/get/byid/'
  partner-create-url: '/partner/create'
  partner-update-url: '/partner/update'
  partner-change-status-url: '/partner//changeStatus'
  partner-review-url: '/partner/review'
  partner-cert-upload-url: '/partner/cert/upload'
  partner-cert-show-url: '/partner/cert/show/'
  pstaff-save-url: '/pstaff/{partnerId}/saveStaff'
  pstaff-delete-url: '/pstaff/{partnerId}/deleteStaff'
  pstaff-updatepwd-url: '/pstaff/{partnerId}/updpwd'
  pstaff-resetpwd-url: '/pstaff/{partnerId}/resetpwd'
  pstaff-upload-url: '/pstaff/{partnerId}/upload/{mode}'
  pstaff-show-url: '/pstaff/{partnerId}/show/{userId}/{mode}'
  pstaff-getall-url: '/pstaff/{partnerId}/getall'

  goods-add-url: '/goods/{partnerId}/add'
  goods-update-url: '/goods/{partnerId}/update'
  goods-get-url: '/goods/get/{goodsId}/{isSelf}/{needPartner}'
  goods-getall-nopartner-url: '/goods/getallnopartner'
  goods-getall-withpartner-url: '/goods/getallwithpartner'
  goods-change-status-url: '/goods/{partnerId}/changeStatus'
  goods-change-spec-url: '/goods/{partnerId}/changeSpec/{goodsId}'
  goods-category-url: '/goods/category'
  
  pimage-file-upload-url: '/pimage/{partnerId}/file/upload'
  pimage-file-show-url: '/pimage/{partnerId}/file/show/{filename}'
  pimage-folder-create-url: '/pimage/{partnerId}/folder/create'
  pimage-folder-list-url: '/pimage/{partnerId}/folder/list'
  
  postage-get-url: '/postage/{partnerId}/get/{postageId}'
  postage-getbypartner-url: '/postage/{partnerId}/getall'
  postage-getusingcnt-url: '/postage/{partnerId}/getusingcnt/{postageId}'
  postage-add-url: '/postage/{partnerId}/add'
  postage-update-url: '/postage/{partnerId}/update'
  postage-delete-url: '/postage/{partnerId}/delete'
  
  receiver-getdefault-url: '/receiver/{userId}/getdefault'
  receiver-getbyuser-url: '/receiver/{userId}/getbyuser'
  receiver-save-url: '/receiver/{userId}/save'
  receiver-delete-url: '/receiver/{userId}/delete/{recvId}'
  receiver-setdefault-url: '/receiver/{userId}/setdefault/{recvId}'
  
  order-get-url: '/order/get/{orderId}'
  order-logistics-url: '/order/logistics/{orderId}'
  order-count-partiby-status-url: '/order/count/partibystatus' 
  order-search-url: '/order/getall' 
  order-create-url: '/order/{userId}/create'
  order-update-url: '/order/{userId}/update'
  order-checkdata-url: '/order/{userId}/checkData' 
  order-prolong-url: '/order/{userId}/prolong/{orderId}'
  order-cancel-url: '/order/{userId}/cancel/{orderId}'
  order-prepay-url: '/order/{userId}/createpay/{orderId}'
  order-pay-finish-url: '/order/{userId}/payfinish/{orderId}'
  order-refund-url: '/order/{userId}/refund/{orderId}'
  order-exchange-url: '/order/{userId}/exchange/{orderId}'
  order-appr2mcht-url: '/order/{userId}/appr2mcht/{orderId}'
  order-appr2user-url: '/order/{partnerId}/appr2user/{orderId}'
  order-ready-url: '/order/{partnerId}/ready/{orderId}'
  order-delivery-url: '/order/{partnerId}/delivery/{orderId}'
  order-updaftersales-url: '/order/{partnerId}/aftersales/{orderId}'
  order-balpay-submit-url: '/order/{userId}/balpay/submit/{orderId}'
  order-payflow-get-url: '/order/{userId}/payflow/{orderId}'
  
  collection-getall-url: '/collection/{userId}/getall'
  collection-getcnt-url: '/collection/{userId}/count'
  collection-add-url: '/collection/{userId}/add'
  collection-delete-url: '/collection/{userId}/delete'
  
  sysparam-getall-url: '/sysparam/sys/getall'
  
  city-get-provinces-url: '/city/province/getall'
  city-get-cities-url: '/city/city/getbyprov/'
  city-get-areas-url: '/city/area/getbycity/'
  
  complain-getall-url: '/complain/getall'
  complain-order-save-url: '/complain/{userId}/order/save'
  complain-partner-save-url: '/complain/{vipId}/partner/save'
  complain-order-delete-url: '/complain/{userId}/order/delete/{cplainId}'
  complain-partner-delete-url: '/complain/{vipId}/partner/delete/{cplainId}' 
  
  cash-apply-url: '/cash/{vipId}/apply'
  cash-delete-url: '/cash/{vipId}/delete'
  cash-update-stat-url: '/cash/updateStat'
  cash-getall-url: '/cash/getall'
   
######系统参数############  
sys:
  local-server-url: 'https://h5.mofangyouxuan.com'
  tmp-file-dir: '/var/mfyxm/tmp/'

  
  
  